import 'package:CaterMe/model/food.dart';

final Fake_Data = [
  Food(
      cuisine: 'italian',
      name: 'Lorem ipsum',
      price: 50,
      image: 'images/food11.jpg',
      description: "Details",
      favorite: false,
      category: ''),
  Food(
      cuisine: 'indian',
      description: "Details",
      favorite: false,
      name: 'Lorem ipsum',
      price: 100,
      image: 'images/food22.webp',
      category: ''),
  Food(
      cuisine: 'lebanese',
      favorite: false,
      description: "Details",
      name: 'Lorem ipsum',
      price: 70,
      image: 'images/food33.jpg',
      category: ''),
  Food(
      description: "Details",
      favorite: false,
      cuisine: 'italian',
      name: 'Lorem ipsum',
      price: 50,
      image: 'images/food11.jpg',
      category: ''),
  Food(
      description: "Details",
      favorite: false,
      cuisine: 'indian',
      name: 'Lorem ipsum',
      price: 100,
      image: 'images/food22.webp',
      category: ''),
  Food(
      cuisine: 'lebanese',
      description: "Details",
      name: 'Lorem ipsum',
      price: 70,
      image: 'images/food33.jpg',
      favorite: false,
      category: ''),
  Food(
      cuisine: 'italian',
      description: "Details",
      name: 'Lorem ipsum',
      favorite: false,
      price: 50,
      image: 'images/food11.jpg',
      category: ''),
  Food(
      cuisine: 'indian',
      favorite: true,
      name: 'Lorem ipsum',
      price: 100,
      description: "Details",
      image: 'images/food22.webp',
      category: ''),
  Food(
      cuisine: 'lebanese',
      name: 'Lorem ipsum',
      favorite: true,
      description: "Details",
      price: 70,
      image: 'images/food33.jpg',
      category: ''),
  Food(
      cuisine: 'italian',
      description: "Details",
      name: 'Lorem ipsum',
      favorite: true,
      price: 50,
      image: 'images/food11.jpg',
      category: ''),
  Food(
      cuisine: 'indian',
      description: "Details",
      name: 'Lorem ipsum',
      price: 100,
      favorite: true,
      image: 'images/food22.webp',
      category: ''),
  Food(
      cuisine: 'lebanese',
      description: "Details",
      name: 'Lorem ipsum',
      price: 70,
      image: 'images/food33.jpg',
      favorite: true,
      category: ''),
  Food(
      cuisine: 'italian',
      description: "Details",
      name: 'Lorem ipsum',
      favorite: true,
      price: 50,
      image: 'images/food11.jpg',
      category: ''),
  Food(
      cuisine: 'indian',
      description: "Details",
      name: 'Lorem ipsum',
      favorite: true,
      price: 100,
      image: 'images/food22.webp',
      category: ''),
  Food(
    favorite: true,
      cuisine: 'lebanese',
      name: 'Lorem ipsum',
      price: 70,
      image: 'images/food33.jpg',
      description: "Details",
      category: ''),
  Food(
      cuisine: 'italian',
      name: 'Lorem ipsum',
      favorite: true,
      description: "Details",
      price: 50,
      image: 'images/food11.jpg',
      category: ''),
  Food(
      cuisine: 'indian',
      name: 'Lorem ipsum',
      favorite: true,
      price: 100,
      description: "Details",
      image: 'images/food22.webp',
      category: ''),
  Food(
      cuisine: 'lebanese',
      name: 'Lorem ipsum',
      favorite: true,
      description: "Details",
      price: 70,
      image: 'images/food33.jpg',
      category: ''),
  Food(
      description: "Details",
      cuisine: 'italian',
      name: 'Lorem ipsum',
      favorite: true,
      price: 50,
      image: 'images/food11.jpg',
      category: ''),
  Food(
      cuisine: 'indian',
      favorite: true,
      name: 'Lorem ipsum',
      description: "Details",
      price: 100,
      image: 'images/food22.webp',
      category: ''),
  Food(
      cuisine: 'lebanese',
      name: 'Lorem ipsum',
      description: "Details",
      favorite: true,
      price: 70,
      image: 'images/food33.jpg',
      category: ''),
];
